# Generated by Django 3.1.4 on 2020-12-15 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('actstream', '0003_add_follow_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='related_action_object_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_action_object', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='action',
            name='related_action_object_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
